# Generated by Django 4.1.3 on 2022-12-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
