# Generated by Django 4.1.3 on 2022-12-03 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_a_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a',
            name='name',
        ),
    ]
