# Generated by Django 4.1.3 on 2022-12-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_remove_a_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='a',
            old_name='age',
            new_name='cnt',
        ),
    ]
