# Generated by Django 4.1.3 on 2022-12-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_rename_age_a_cnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='air_set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.IntegerField(default=1)),
                ('temp', models.IntegerField(default=25)),
            ],
        ),
        migrations.CreateModel(
            name='week_set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_1', models.TimeField()),
                ('off_1', models.TimeField()),
            ],
        ),
    ]
