# Generated by Django 4.1.3 on 2022-12-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_air_set_week_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='air_set',
            name='speed',
            field=models.IntegerField(default=4),
        ),
    ]
