# Generated by Django 4.1.3 on 2022-12-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_air_set_speed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='week_set',
            old_name='off_1',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='week_set',
            name='on_1',
        ),
        migrations.AddField(
            model_name='week_set',
            name='day',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week_set',
            name='if_on',
            field=models.IntegerField(default=0),
        ),
    ]
