# Generated by Django 4.1.3 on 2022-12-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_rename_off_1_week_set_time_remove_week_set_on_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='week_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestart', models.IntegerField(default=0)),
                ('time_week', models.IntegerField(default=0)),
                ('if_on', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='air_set',
            name='if_on',
            field=models.IntegerField(default=0),
        ),
    ]
