# Generated by Django 4.1.3 on 2022-12-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_week_time_air_set_if_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week_time',
            name='time_week',
        ),
        migrations.RemoveField(
            model_name='week_time',
            name='timestart',
        ),
        migrations.AddField(
            model_name='week_time',
            name='times_start',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='week_time',
            name='times_start_show',
            field=models.CharField(default='00:00', max_length=20),
        ),
        migrations.AddField(
            model_name='week_time',
            name='week_num',
            field=models.CharField(default='周一', max_length=20),
        ),
    ]
