# Generated by Django 4.1.3 on 2022-12-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_remove_week_time_time_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='week_set',
            name='pref',
            field=models.IntegerField(default=0),
        ),
    ]
