# Generated by Django 4.1.3 on 2022-12-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_week_set_on_off'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week_set',
            name='on_off',
        ),
        migrations.RemoveField(
            model_name='week_set',
            name='pref',
        ),
        migrations.AddField(
            model_name='air_set',
            name='on_off',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='air_set',
            name='pref',
            field=models.IntegerField(default=0),
        ),
    ]
